"""empty message

Revision ID: 59bc5b8c9233
Revises: e3ef5e4bceb8
Create Date: 2023-01-18 08:51:10.047981

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '59bc5b8c9233'
down_revision = 'e3ef5e4bceb8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bus_stop_direction', 'is_last')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bus_stop_direction', sa.Column('is_last', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
