"""empty message

Revision ID: 7fbf5be2d9b8
Revises: 59bc5b8c9233
Create Date: 2023-01-18 10:32:28.150782

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fbf5be2d9b8'
down_revision = '59bc5b8c9233'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'direction', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'direction', type_='unique')
    # ### end Alembic commands ###
