"""empty message

Revision ID: e3ef5e4bceb8
Revises: 
Create Date: 2023-01-17 21:48:40.029295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3ef5e4bceb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bus',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_stop',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('direction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_direction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.String(length=255), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_stop_bus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_id', sa.String(length=255), nullable=True),
    sa.Column('bus_stop_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['bus.id'], ),
    sa.ForeignKeyConstraint(['bus_stop_id'], ['bus_stop.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bus_stop_direction',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_stop_id', sa.String(length=255), nullable=True),
    sa.Column('direction_id', sa.Integer(), nullable=True),
    sa.Column('is_last', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['bus_stop_id'], ['bus_stop.id'], ),
    sa.ForeignKeyConstraint(['direction_id'], ['direction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus_stop_direction')
    op.drop_table('bus_stop_bus')
    op.drop_table('bus_direction')
    op.drop_table('direction')
    op.drop_table('bus_stop')
    op.drop_table('bus')
    # ### end Alembic commands ###
