name: Build and deploy

on:
  push:
    branches:
      - main

env:
  SSH_OPTS: "-o StrictHostKeyChecking=no"

jobs:
  deploy-api:
    name: Deploy API
    runs-on: ubuntu-latest
    steps:
      - name: Install OpenSSH client
        run: |
          sudo apt-get update -y
          sudo apt-get install openssh-client -y

      - name: Set up SSH
        run: |
          eval "$(ssh-agent -s)"
          ssh-add <(echo -e "$SSH_PRIVATE_KEY")

      - name: Deploy API to remote server
        run: |
          sshpass -p $SSH_USER ssh $SSH_USER@$DEPLOY_SERVER 'cd $PROJECT_PATH && git pull && docker-compose up -d --no-deps --build docker-api'
